services:
    postit.mongodb_client.factory:
        class: PostIt\Factory\MongoDBClientFactory
        arguments: [%database_name%, %postit_collection%]
    postit.mongodb_client:
        class: Postit\Service\MongoDBClient
        factory: ['@postit.mongodb_client.factory', create]

    postit.event_listener:
        class: PostIt\EventListener\ResponseEventListener
        tags:
            - { name: kernel.event_listener, method: onKernelResponse, event: kernel.response }


    postit.event_request_listener:
        class: PostIt\EventListener\RequestEventListener
        tags:
            - { name: kernel.event_listener, method: onKernelException, event: kernel.exception }