# To get started with security, check out the documentation:
# http://symfony.com/doc/current/book/security.html
security:

    # http://symfony.com/doc/current/book/security.html#where-do-users-come-from-user-providers
    providers:
        in_memory:
            memory:
                users:
                    front:
                        password: frontPourNaze
                        roles: ['ROLE_FRONTEND']
                    back:
                        password: backPourTrav
                        roles: ['ROLE_BACKEND']
                    doc:
                        password: doc
                        roles: ['ROLE_DOC']

    encoders:
            Symfony\Component\Security\Core\User\User: plaintext

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        api:
            pattern: ^/
            anonymous: true
            http_basic: ~
            # activate different ways to authenticate

            # http_basic: ~
            # http://symfony.com/doc/current/book/security.html#a-configuring-how-your-users-will-authenticate

            # form_login: ~
            # http://symfony.com/doc/current/cookbook/security/form_login_setup.html

    role_hierarchy:
        ROLE_BACKEND: [ROLE_USER]
        ROLE_FRONTEND: [ROLE_USER]
        ROLE_DOC: [ROLE_BACKEND, ROLE_FRONTEND]

    access_control:
        - {path: ^/api/doc, roles: ['ROLE_DOC']}
        - {path: ^/, roles: ['ROLE_USER']}

